// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lredbctdgicaohdvbnvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyZWRiY3RkZ2ljYW9oZHZibnZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyOTYzNjgsImV4cCI6MjA1NDg3MjM2OH0.scaO6Zeru5Q4cy9jk46AVj3qz9F_cpyZEa7o_84vdD0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);